/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package compiler

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun calculateTheAnswer() = 42
}
